services:
  keep-frontend-dev:
    extends:
      file: docker-compose.common.yml
      service: keep-frontend-common
    environment:
      - API_URL=http://keep-backend-dev:8080
      - SENTRY_DISABLED=true
      - AUTH_TYPE=DB
    build:
      dockerfile: docker/Dockerfile.dev.ui
    volumes:
      - ./keep-ui:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - keep-backend-dev

  keep-backend-dev:
    extends:
      file: docker-compose.common.yml
      service: keep-backend-common
    environment:
      - AUTH_TYPE=DBMT
      - KEEP_DEFAULT_USERNAME=keep@keep
      - KEEP_DEFAULT_PASSWORD=keep
      - KEEP_JWT_SECRET=keepsupersecret
    build:
      dockerfile: docker/Dockerfile.dev.api
    volumes:
      - .:/app
      - ./state:/state

  keep-websocket-server:
    extends:
      file: docker-compose.common.yml
      service: keep-websocket-server-common
